### PR TITLE
Add 5.15.5 release.

### PR DESCRIPTION
**Pull request by splatch**

### CODE REVIEW

**Comment by rmohr** [comment]
@splatch thanks, could you add the new version to .travis.yml?

**Comment by splatch** [comment]
Updated travis configuration, changes are separated per commit/version basis so you will get a merge conflict depending on approval order.

**Comment by rmohr** [comment]
@splatch travis thinks that there is something wrong with the checksum. Could you have another look?

**Comment by splatch** [comment]
Sure, let me address this one.

**Comment by rmohr** [comment]
and you can rebase now, since your other PR is merged.

**Comment by splatch** [comment]
Rebased. Apparently by mistake I picked up wrong SHA for ZIP archives.

**Review by rmohr — APPROVED** [review]

**Comment by rmohr** [comment]
@splatch thanks again. Images are currently building.

**Comment by splatch** [comment]
Thank you very much for merging and feedback!

**Pull request merged**
