### PR TITLE
[RFC] Add support for 5.16.0

### LINKED ISSUE #60: Support for ActiveMQ 5.16.0 (Jul 1, 2020)
Hi, great work!
Please consider releasing the latest activemq.

Latest release is ActiveMQ 5.16.0 (Jul 1, 2020)

### PR DESCRIPTION
**Pull request by carantunes**
Hi,
Adding support for 5.16.0.

Closes https://github.com/rmohr/docker-activemq/issues/60

### CODE REVIEW

**Comment by carantunes** [comment]
Can you add the label `hacktoberfest-accepted` to this PR?

**Comment by TBG-FR** [comment]
I just tried it, not working (nothing under http://localhost:8161/ ), whereas it works well with the latest docker image (`5.15.9`)

**Comment by carantunes** [comment]
Hi @rmohr, could you trigger again the jobs that failed? They failed due "too many requests"

**Comment by okorz001** [comment]
Is there any update on this? I am very interested in a 5.16 image. Actually 5.16.1 has already been released since this PR was opened.

@carantunes maybe you could try kicking travis by force-pushing a new ~comment~ commit.

**Comment by rmohr** [comment]
@carantunes sorry for not being responsive, I don't use this repo for years now. It is basically unmaintained.

**Comment by rmohr** [comment]
If travis becomes green I can merge and check if I can get it published, but no promises.

**Comment by carantunes** [comment]
Thank you @rmohr! Have you considered adding new maintainers? Alternatively I will look into forks/forking it.

**Comment by filviu** [comment]
> Thank you @rmohr! Have you considered adding new maintainers? Alternatively I will look into forks/forking it.

I'm interested in maintaining this further too. @rmohr are you considering adding maintainers or you would prefer people to just fork away :) ?

**Comment by rmohr** [comment]
Thanks you for your contribution.

As you probably noticed, I am not using this repo myself anymore for a long time and fail to find the time to maintain it for quite some time now too. Please consider using a fork. This repo is unmaintained and I am going to archive it soon.

**Pull request closed without merging**
